spring.datasource.url=jdbc:postgresql://localhost:5433/form
spring.datasource.username=postgres
spring.datasource.password=1
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri= http://localhost:8080/realms/Forms
spring.security.oauth2.resourceserver.jwt.jwk-set-uri= http://localhost:8080/realms/Forms/protocol/openid-connect/certs
jwt.auth.converter.resource-id: forms-rest-api
jwt.auth.converter.principle-attribute: preferred_username